name = "lapce-tsserver"
display-name = "JavaScript/TypeScript"
description = "JS/TS for Lapce: powered by TSServer"
version = "0.1.0"
author = "Chirok11"
repository = "chirok11/lapce-tsserver"
wasm = "lapce-tsserver.wasm"

[configuration]
language_id = "javascript"

# [configuration.options.diagnostics]
# enable = false
# enableExperimental = false
[configuration.options.binary]
args = ["--stdio"]